### ISSUE TITLE
Unhandled rejection Error

### ISSUE THREAD

**Issue by jegj** [taxjar/taxjar-node#9]
i have problems with the new update. i get an anonymous error on node_modules/taxjar/lib/util/request.js:25:30. This problem only happens with the new version on taxjar, if i used a previous version works fine.

`Unhandled rejection Error
    at Request.<anonymous> (/home/vagrant/vcoplayer/node_modules/taxjar/lib/util/request.js:25:30)
    at emitTwo (events.js:100:13)
    at Request.emit (events.js:185:7)
    at Request.mixin._fireSuccess (/home/vagrant/vcoplayer/node_modules/restler/lib/restler.js:229:10)
    at /home/vagrant/vcoplayer/node_modules/restler/lib/restler.js:161:20
    at IncomingMessage.parsers.json (/home/vagrant/vcoplayer/node_modules/restler/lib/restler.js:415:9)
    at IncomingMessage.parsers.auto (/home/vagrant/vcoplayer/node_modules/restler/lib/restler.js:400:21)
    at Request.mixin._encode (/home/vagrant/vcoplayer/node_modules/restler/lib/restler.js:198:29)
    at /home/vagrant/vcoplayer/node_modules/restler/lib/restler.js:157:16
    at Request.mixin._decode (/home/vagrant/vcoplayer/node_modules/restler/lib/restler.js:173:7)
    at IncomingMessage.<anonymous> (/home/vagrant/vcoplayer/node_modules/restler/lib/restler.js:150:14)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:913:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
From previous event:
    at Object.Request.api (/home/vagrant/vcoplayer/node_modules/taxjar/lib/util/request.js:14:12)
    at Object.Taxjar.taxForOrder (/home/vagrant/vcoplayer/node_modules/taxjar/lib/taxjar.js:47:25)
    at next (/home/vagrant/vcoplayer/server/lib/checkout/index.js:135:10)
    at /home/vagrant/vcoplayer/server/controllers/checkout/calculateTaxes.js:18:4
    at /home/vagrant/vcoplayer/server/models/user.js:214:11
    at Query.<anonymous> (/home/vagrant/vcoplayer/node_modules/mongoose/lib/model.js:3407:16)
    at /home/vagrant/vcoplayer/node_modules/kareem/index.js:259:21
    at /home/vagrant/vcoplayer/node_modules/kareem/index.js:127:16
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
`

**Comment by fastdivision** [comment]
Hi @jegj! We recently improved the way we handle errors to properly reject promises with a proxied `Error` instance. You need to handle rejected promises with a catch handler:

```
taxjar.taxForOrder({
  from_country: 'US',
  from_zip: '07001',
  from_state: 'NJ',
  to_country: 'US',
  to_zip: '07446',
  to_state: 'NJ',
  amount: 16.50,
  shipping: 1.5,
  line_items: [
    {
      quantity: 1,
      unit_price: 15.0,
      product_tax_code: 31000
    }
  ]
}).then(function(res) {
  res.tax; // Tax object
  res.tax.amount_to_collect; // Amount to collect
}).catch(function(err) {
  err.detail; // Error detail
  err.status; // Error status code
});
```
